### ISSUE TITLE
[Ubuntu Budgie 20.04] Runs ok but when I Apply my changes it does nothing

### ISSUE THREAD

**Issue by serber1990** [hhannine/superpaper#110]
**Describe the bug**
The program runs correctly but when I select every source for each monitor (I have 4) in the "Separate Image for every Display" option, whenever I click "Apply" doesn't change anything.

My display manager is Lightdm (Default on Budgie) so there is no option to set "span" for the backgrounds. I installed gnome-tweak-tools and set the option of the background to "Spanned" and it changed my actual default background size but it won't apply my Profile set-up on Superpaper.

**To Reproduce**
1. Open the app
2. Select option 'Separate image for every display'
3. Browse and select every background for each monitor (Displays 0 to 3)
4. Saved my Profile with a name, and Click apply
5. No errors found when executed from terminal with "-d"
6. Nothing changes on my backgrounds

**Expected behavior**
I expected to see the 4 wallpapers on each of my monitors

**Desktop (please complete the following information):**
 - OS: [Ubuntu Budgie 20.04]
 - Desktop Environment on Linux: [Lightdm]
 - Superpaper package & version: [Superpaper-2.1.0-x86_64.AppImage & Superpaper-2.1.0-x86_64.AppImage-ubuntu1604-base.AppImage]

Any ideas?

**Comment by hhannine** [comment]
Post here the output from the debug prints when you run Superpaper with the debug option "-d". Might be that something has broken support on Budgie.

Have you tried using the "Simple  span" mode to see if that works?

**Comment by serber1990** [comment]
/tmp/.mount_SuperpcKZk7T/usr
/home/serber/.config/superpaper
/home/serber/.config/superpaper/profiles
GLib-GIO-Message: 12:19:16.244: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
None
None
None
None
None
None
True
Gtk-Message: 12:19:16.247: Failed to load module "appmenu-gtk-module"

(Superpaper-2.1.0-x86_64.AppImage:47837): GdkPixbuf-WARNING **: 12:19:16.256: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
START Listing profiles for menu.
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
END Listing profiles for menu.
No previous profile was found.
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Registering binding:                                 None for profile: Serber
Registering binding:                                 None for profile: Simple
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')

**Comment by serber1990** [comment]
> Post here the output from the debug prints when you run Superpaper with the debug option "-d". Might be that something has broken support on Budgie.
> 
> Have you tried using the "Simple span" mode to see if that works?

Yes, I used the Simple Span mode with 1 picture and it didn't work either

**Comment by hhannine** [comment]
Did you post all the debug log? Seems that it cuts of just  before the bits I wanted to see. What Python version are you using?

**Comment by serber1990** [comment]
> Did you post all the debug log? Seems that it cuts of just before the bits I wanted to see. What Python version are you using?

Yes I posted everything I get on my terminal.

Right now I have Python 3.8.10 installed.

Maybe i'm doing something wrong, can you tell me exactly what command should I run to get those lines you miss? 

I'm running ./Superpaper.......etc.......AppImage -d

**Comment by hhannine** [comment]
That should be it. Does Superpaper terminate at that point in the log or does it keep running? Did you try applying a profile while the logging was running?

Could you also run `echo $DESKTOP_SESSION` in the terminal and post the output?

**Comment by serber1990** [comment]
> That should be it. Does Superpaper terminate at that point in the log or does it keep running? Did you try applying a profile while the logging was running?
> 
> Could you also run `echo $DESKTOP_SESSION` in the terminal and post the output?

Here's the Debug when I try to apply all 4 wallpapers...

10:23:01 ✘ serber:~/Descargas$ ./Superpaper-2.1.0-x86_64.AppImage -d
/tmp/.mount_SuperpuPD7EG/usr
/home/serber/.config/superpaper
/home/serber/.config/superpaper/profiles
GLib-GIO-Message: 10:23:26.745: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
None
None
None
None
None
None
True
Gtk-Message: 10:23:26.747: Failed to load module "appmenu-gtk-module"

(Superpaper-2.1.0-x86_64.AppImage:6868): GdkPixbuf-WARNING **: 10:23:26.756: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
START Listing profiles for menu.
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
END Listing profiles for menu.
No previous profile was found.
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Registering binding:                                 None for profile: Serber
Registering binding:                                 None for profile: Simple
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
Serber
multi
False
None
None
None
None
['/home/serber/Imágenes/iphone-ios-ipad-ipod-wallpaper-preview.jpg', '/home/serber/Imágenes/wallpaperflare.com_wallpaper1.jpg', '/home/serber/Imágenes/wallpaperflare.com_wallpaper.jpg', '/home/serber/Imágenes/rick-sanchez-easier-for-you-wallpaper.jpg']
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'w')
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Registering binding:                                 None for profile: Serber
Registering binding:                                 None for profile: Simple
perspective preset: default
onApply profile: saved /home/serber/.config/superpaper/profiles/Serber.profile
perspective preset: default
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Start profile: Serber
Running quick profile job with profile: Serber
quickswitch file lookup: []
Old file for quickswitch was not found. []
Starting timed profile job with profile: Serber
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
running profile job with profile: Serber
Running a one-off wallpaper change.
['/home/serber/Imágenes/iphone-ios-ipad-ipod-wallpaper-preview.jpg', '/home/serber/Imágenes/wallpaperflare.com_wallpaper1.jpg', '/home/serber/Imágenes/wallpaperflare.com_wallpaper.jpg', '/home/serber/Imágenes/rick-sanchez-easier-for-you-wallpaper.jpg']
Wrote active profile: Serber
Canvas size: [4920, 3564]
file:///home/serber/.cache/superpaper/temp/Serber-a.png
DESKTOP_SESSION is: 'budgie-desktop'

**Comment by hhannine** [comment]
Thanks. It might be an issue with the way superpaper is trying to set the wallpaper via a terminal call. Do you know of a working terminal command to set the wallpaper on Budgie?

**Comment by serber1990** [comment]
> Thanks. It might be an issue with the way superpaper is trying to set the wallpaper via a terminal call. Do you know of a working terminal command to set the wallpaper on Budgie?

That is a good question. I searched around a bit but I can't seem to find anything. Maybe there is no command, or maybe there is no one asking this question yet.

**Comment by fossfreedom** [comment]
> Do you know of a working terminal command to set the wallpaper on Budgie?

It is exactly the same as GNOME

    gsettings set org.gnome.desktop.background picture-uri file:///usr/share/backgrounds/mywallpaper.jpg

**Comment by hhannine** [comment]
Thanks @fossfreedom for confiming it. That is what Superpaper is using as well so it is now unclear what is causing the issue for @serber1990.

@serber1990 can you test the command shown above in the terminal to verify that it does work for you?

**Comment by hhannine** [comment]
Alternatively, @fossfreedom is Superpaper working for you on Budgie?

**Comment by serber1990** [comment]
> Thanks @fossfreedom for confiming it. That is what Superpaper is using as well so it is now unclear what is causing the issue for @serber1990.
> 
> @serber1990 can you test the command shown above in the terminal to verify that it does work for you?

It changes my wallpaper but, it won't take the images I select in the picture-uri path, it just leaves the default one

**Comment by hhannine** [comment]
I wonder if the problem could be with the special characters in the path name that is shown in the debug log? Could you try to run the terminal command but on an image that is in your home directory or other path with only english characters?

**Comment by serber1990** [comment]
> I wonder if the problem could be with the special characters in the path name that is shown in the debug log? Could you try to run the terminal command but on an image that is in your home directory or other path with only english characters?

Here's the result -d of what you told me to try.. I used the same wallpapers directly from home directory so I avoid the Spanish accents on some letters, but, same result, nothing is applied to my desktop..

The curious thing is that HydraPaper does apply my wallpapers correctly but I'll prefer to make it work with Superpaper instead

/tmp/.mount_SuperpjuBoKl/usr
/home/serber/.config/superpaper
/home/serber/.config/superpaper/profiles
GLib-GIO-Message: 16:10:23.900: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
None
None
None
None
None
None
True
Gtk-Message: 16:10:23.903: Failed to load module "appmenu-gtk-module"

(Superpaper-2.1.0-x86_64.AppImage:186493): GdkPixbuf-WARNING **: 16:10:23.909: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
START Listing profiles for menu.
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
END Listing profiles for menu.
read profile name from 'running_profile': Serber
perspective preset: default
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
running profile job with profile: Serber
Running a one-off wallpaper change.
['/home/serber/iphone-ios-ipad-ipod-wallpaper-preview.jpg', '/home/serber/wallpaperflare.com_wallpaper1.jpg', '/home/serber/wallpaperflare.com_wallpaper.jpg', '/home/serber/rick-sanchez-easier-for-you-wallpaper.jpg']
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Registering binding:                                 None for profile: Serber
Registering binding:                                 None for profile: Simple
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
Canvas size: [4920, 3564]
file:///home/serber/.cache/superpaper/temp/Serber-a.png
DESKTOP_SESSION is: 'budgie-desktop'
GLib-GIO-Message: 16:10:28.961: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(process:186539): GLib-GIO-WARNING **: 16:10:28.961: unknown schema extension 'd'

(process:186539): GLib-GIO-WARNING **: 16:10:28.961: unknown schema extension 'd'
Serber
multi
False
None
None
None
None
['/home/serber/iphone-ios-ipad-ipod-wallpaper-preview.jpg', '/home/serber/wallpaperflare.com_wallpaper1.jpg', '/home/serber/wallpaperflare.com_wallpaper.jpg', '/home/serber/rick-sanchez-easier-for-you-wallpaper.jpg']
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'w')
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Registering binding:                                 None for profile: Serber
Registering binding:                                 None for profile: Simple
perspective preset: default
onApply profile: saved /home/serber/.config/superpaper/profiles/Serber.profile
perspective preset: default
perspective preset: default
Listed profile: Serber
perspective preset: default
Listed profile: Simple
Start profile: Serber
Check if the starting profile is already running: Serber
name check: Serber, Serber
Running quick profile job with profile: Serber
quickswitch file lookup: ['Serber-a.png']
file:///home/serber/.cache/superpaper/temp/Serber-a.png
Starting timed profile job with profile: Serber
DESKTOP_SESSION is: 'budgie-desktop'
GLib-GIO-Message: 16:10:32.980: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(process:186550): GLib-GIO-WARNING **: 16:10:32.980: unknown schema extension 'd'

(process:186550): GLib-GIO-WARNING **: 16:10:32.980: unknown schema extension 'd'
WARNING: Horizontal and vertical PPI do not match! hor: 91.66917293233082, ver: 90.23684210526315
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
get_display_data output: NUM_DISPLAYS = 4, RES_ARR = [(1080, 1920), (3840, 2160), (1920, 1080), (1920, 1080)], OFF_ARR = [(0, 1644), (1080, 0), (1080, 2160), (3000, 2160)]
Display(resolution=(1080, 1920), digital_offset=(0, 1644), phys_size_mm=(268, 476), detected_phys_size_mm=(268, 476), ppi=102.35820895522387, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-1')
Display(resolution=(3840, 2160), digital_offset=(1080, 0), phys_size_mm=(1600, 900), detected_phys_size_mm=(1600, 900), ppi=60.959999999999994, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-2')
Display(resolution=(1920, 1080), digital_offset=(1080, 2160), phys_size_mm=(480, 270), detected_phys_size_mm=(480, 270), ppi=101.6, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
Display(resolution=(1920, 1080), digital_offset=(3000, 2160), phys_size_mm=(532, 304), detected_phys_size_mm=(532, 304), ppi=91.66917293233082, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DisplayPort-0')
load_system: archive_file not found: /home/serber/.config/superpaper/display_systems.dat
running profile job with profile: Serber
Running a one-off wallpaper change.
['/home/serber/iphone-ios-ipad-ipod-wallpaper-preview.jpg', '/home/serber/wallpaperflare.com_wallpaper1.jpg', '/home/serber/wallpaperflare.com_wallpaper.jpg', '/home/serber/rick-sanchez-easier-for-you-wallpaper.jpg']
Wrote active profile: Serber
Canvas size: [4920, 3564]
file:///home/serber/.cache/superpaper/temp/Serber-b.png
DESKTOP_SESSION is: 'budgie-desktop'
GLib-GIO-Message: 16:10:37.259: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

**Comment by hhannine** [comment]
Thanks for the log. It looks like you're suffering from the Glib-GIO issue mentioned in the known-issues doc:
try to run superpaper with
`GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/ superpaper`

**Comment by hhannine** [comment]
Might this be resolved by the above comment? I have tried to resolve the above issue now, hopefully for good, fix will be in next release. If this is still an open problem, please come comment or reopen the issue.

**Comment by serber1990** [comment]
Hello, this is not resolved yet as I don't really understand how to execute that... Do I have to put that entire line before the -d?

Sorry I didn't had time to answer before

**Comment by serber1990** [comment]
This is what I get when I execute with that line before:

GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/ ./Superpaper-2.1.0-x86_64.AppImage
/tmp/.mount_SuperpfqtWgr/usr
/home/serber/.config/superpaper
/home/serber/.config/superpaper/profiles
/tmp/_MEI3hf9To/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
Gtk-Message: 22:55:20.084: Failed to load module "appmenu-gtk-module"
/tmp/_MEI3hf9To/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so

(Superpaper-2.1.0-x86_64.AppImage:5316): GdkPixbuf-WARNING **: 22:55:20.094: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
/tmp/_MEI3hf9To/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so

**Comment by hhannine** [comment]
Ok thanks and no problem. You ran it correctly as intended. I've not seen this type of failure before, unfortunately.

Have you tried using the pip installation of superpaper?

**Comment by serber1990** [comment]
No actually. I didn't knew you had one. Is there a step by step somewhere to look for?

**Comment by hhannine** [comment]
Yes check this out https://github.com/hhannine/superpaper/blob/master/docs/installation-linux.md

**Comment by serber1990** [comment]
If I knew this from the beggining we would have saved both of our times.

Now it works like a charm...

Thank you very much for all the effort both making this and helping us.

If I were not poor I would became a sponsor man..

**Comment by hhannine** [comment]
Thanks a lot. Great to hear that you got it working.

The issue you had with the Appimage has been hard to solve unfortunately since it is the act of packaging the appimage which is causing the problem with interfacing with the host system. The pip version naturally does not run into this so it has always been more problem-free.
