### ISSUE TITLE
Will no longer autostart at logon

### ISSUE THREAD

**Issue by Roy-Orbison** [hhannine/superpaper#133]
Since KDE switched to a systemd boot, many `.desktop` files that were previously okay [stopped working][0]. For me, `journalctl` logs this line:
```text
Dec 15 09:53:31 Roybook systemd-xdg-autostart-generator[1523]: /home/roy/.config/autostart/superpaper.desktop: not generating unit, error parsing Exec= line: No such file or directory
```
I assume the user-local `$PATH` isn't available (at least at that point in time).

Another python app – that was similarly failing but now works – generates this launcher file:
```ini
[Desktop Entry]
Version=1.0
Type=Application
Name=Maestral
Exec=/usr/bin/python3 -m maestral_qt -c maestral
Icon=maestral
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=2
X-KDE-autostart-after=panel
```

Perhaps you could modify yours to include the same dependency fixes and delay?

  [0]: https://bugs.kde.org/show_bug.cgi?id=455252

**Comment by hhannine** [comment]
Thanks a lot for the report and suggestion! This issue has been bugging me as well on my KDE machine and I didn't know where to look for the problem, other than that it's related to the systemd boot change. I'll test your suggested changes when I can.

**Comment by hhannine** [comment]
This is now resolved with 299f7e52d9b3b317db4c098e3b5a283450ca0385
Thanks again!

**Comment by Roy-Orbison** [comment]
I upgraded to v2.2.1, and the `.desktop` file in my local config definitely has your fix, but it still does not show any icon in the status/notification area. Is it not meant to? There are no processes listed in `ps` that have `superpaper` in the command/args, nor any python instances that belong to my user id, **but** the systemd log no longer has an error and does show this:
```text
systemd[1484]: Starting Superpaper...
...
systemd[1484]: Started Superpaper.
```

**Comment by hhannine** [comment]
Hmm unfortunate. For me the autostart issue was fixed on manjaro kde. Have you tried recreating the auto start entry in kde settings?

**Comment by Roy-Orbison** [comment]
I did not. Oops. I symlinked to the one in `~/.local/share/applications/`, which I assume will fix it next logon.
